$axure.loadCurrentPage({
  "url":"首页.html",
  "generationDate":new Date(1395018284654.33),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"826a6709258741c1af63d394cb37a814",
    "type":"Axure:Page",
    "name":"首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFEEEEEE},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cfc47f7acffc4bc7abeb906cf3186d7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":292},
            "size":{
              "width":315,
              "height":315},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c3c404bd03f4790826d4daa46fc34c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":292},
                "size":{
                  "width":315,
                  "height":315},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"3e0f518627f34f269c3089e0e5bcfc16",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":6,
              "y":605},
            "size":{
              "width":315,
              "height":327},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3242b5daa8f14b14936d0082ea94c8ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":6,
                  "y":605},
                "size":{
                  "width":315,
                  "height":327},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"1ae22279759a48bca60aecc6461c8255",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":5,
              "y":127},
            "size":{
              "width":315,
              "height":155},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2d408f0d77e4d9a9f81a19d99394778",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":5,
                  "y":127},
                "size":{
                  "width":315,
                  "height":155},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"3b3787f8e52c48e0ac23b67c146ce749",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":5,
              "y":2},
            "size":{
              "width":315,
              "height":125}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9980d90cee614bd096c24d8ac3f26ab5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":5,
                  "y":2},
                "size":{
                  "width":315,
                  "height":125}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u6.jpg"}},
{
          "id":"3f55cd157a2a41b199efbc9141a95c62",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":25,
              "y":158},
            "size":{
              "width":200,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d305a70506da4c969120652473b85bf6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":25,
                  "y":158},
                "size":{
                  "width":200,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5cc7351b96cf47e599b6e2d1cbb17eef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"18px",
            "fontWeight":"200",
            "location":{
              "x":25,
              "y":134},
            "size":{
              "width":240,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07b53e9df51f4c90a5d823c102d99c70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"18px",
                "fontWeight":"200",
                "location":{
                  "x":25,
                  "y":134},
                "size":{
                  "width":240,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a25e910762f44e7eb5b043f551ee32e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"18px",
            "fontWeight":"200",
            "location":{
              "x":25,
              "y":183},
            "size":{
              "width":260,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14aa7831a8104b2ca88c761ad6cb3391",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"18px",
                "fontWeight":"200",
                "location":{
                  "x":25,
                  "y":183},
                "size":{
                  "width":260,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"645c2df6452f44db94763dc587404b63",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":25,
              "y":206},
            "size":{
              "width":221,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8362150de7694d5ba1515cc22eac2427",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":25,
                  "y":206},
                "size":{
                  "width":221,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e31f52dba744371950f7736dc1d44c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":60,
              "y":237},
            "size":{
              "width":250,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd29b1d518c84c53b113c5bdb3c3542d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":60,
                  "y":237},
                "size":{
                  "width":250,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 商品详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"商品详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u16.png"}},
{
          "id":"b77385143ba94aeebece268eac84e5b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":239},
            "size":{
              "width":25,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"50"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57eb1ae4a76c4f4b9c78c973af103aa0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":239},
                "size":{
                  "width":25,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"50"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u18.png"}},
{
          "id":"15b8735f1e014eceb10e4f0e83b2f20a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":278,
              "y":242},
            "size":{
              "width":12,
              "height":10},
            "rotation":"45",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9900}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 商品详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"商品详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u20_line.png"}},
{
          "id":"da9763411cc5476e8fc7804688a3811f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":278,
              "y":250},
            "size":{
              "width":12,
              "height":10},
            "rotation":"135",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9900}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 商品详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"商品详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u20_line.png"}},
{
          "id":"c49e9f32dc6640d581a26c24532d9cf7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":298},
            "size":{
              "width":300,
              "height":300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8449efe5a49f442b9757657a68f22fca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":298},
                "size":{
                  "width":300,
                  "height":300}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 商品详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"商品详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u22.jpg"}},
{
          "id":"f3c8606e28054e119432a5b07edca68b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"18px",
            "fontWeight":"200",
            "location":{
              "x":15,
              "y":617},
            "size":{
              "width":285,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c27fc32c7154fc48f7354e0e946cefa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"18px",
                "fontWeight":"200",
                "location":{
                  "x":15,
                  "y":617},
                "size":{
                  "width":285,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 商品详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"商品详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7cb57bc65dd145e7939c558d0e344e41",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":15,
              "y":646},
            "size":{
              "width":277,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f6bafa65a284569b59d8574fe47e40d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":15,
                  "y":646},
                "size":{
                  "width":277,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74d3ed46b5644bfcb0708b2a83bd6231",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "lineSpacing":"18px",
            "location":{
              "x":13,
              "y":695},
            "size":{
              "width":285,
              "height":162}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ec11e1a14f24e33a4e38eaf3bfa592f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "lineSpacing":"18px",
                "location":{
                  "x":13,
                  "y":695},
                "size":{
                  "width":285,
                  "height":162}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"854b878d27e3459387fe25e3e392013c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":867},
            "size":{
              "width":305,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u30_line.png"}},
{
          "id":"280ba8153ce74b0f90ceb437be715614",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Medium', 'Heiti SC Medium', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":12,
              "y":884},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9443210395ca45a29cd9268f02c866a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Medium', 'Heiti SC Medium', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":12,
                  "y":884},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e2923bb345a4b11884eef2a9aee5b4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCC0000,
              "opacity":1},
            "location":{
              "x":63,
              "y":881},
            "size":{
              "width":68,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e81a48cd3374891b23ac046bc751b58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000,
                  "opacity":1},
                "location":{
                  "x":63,
                  "y":881},
                "size":{
                  "width":68,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca9c0a52f4ca433f851fa740a0e49575",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":12,
              "y":904},
            "size":{
              "width":93,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"212fffaa30af4fd8893524dac4a14815",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":12,
                  "y":904},
                "size":{
                  "width":93,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae9bf93e4a19462ba76f325d3e3a56dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":200,
              "y":884},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b62795b912cf4979aa57a3121c8948e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":200,
                  "y":884},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 结算 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"结算.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u37.png"}},
{
          "id":"6e26fd7ebbcd45f18ca83aafda49119a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":942},
            "size":{
              "width":315,
              "height":315},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a16df7f4dca45a2a3116156bfce5f0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":942},
                "size":{
                  "width":315,
                  "height":315},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"5b72c6e2da0e4627870d8a0d5c5e36be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":6,
              "y":1255},
            "size":{
              "width":315,
              "height":327},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63bc27e2203644699398871e0731834a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":6,
                  "y":1255},
                "size":{
                  "width":315,
                  "height":327},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"0eef2249f33946e9819ffe483b0a2872",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":948},
            "size":{
              "width":300,
              "height":300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18785ecb6e7b446fac7f03483f49cf32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":948},
                "size":{
                  "width":300,
                  "height":300}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 商品详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"商品详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u22.jpg"}},
{
          "id":"3be32eaf6581446bbc6417f32f1205e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"18px",
            "fontWeight":"200",
            "location":{
              "x":15,
              "y":1267},
            "size":{
              "width":285,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9efc2efd5cc40d28ed7c884cc70ce93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"18px",
                "fontWeight":"200",
                "location":{
                  "x":15,
                  "y":1267},
                "size":{
                  "width":285,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 商品详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"商品详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39a423e8376c400ea6dfb6fdbd9c9bda",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":15,
              "y":1296},
            "size":{
              "width":277,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18be4999036e4bb4894bfc5aa49af642",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":15,
                  "y":1296},
                "size":{
                  "width":277,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d61897580aee4bda8bd0e19d8ea3db0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "lineSpacing":"18px",
            "location":{
              "x":13,
              "y":1345},
            "size":{
              "width":285,
              "height":162}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0baaa14c590405f988db3b0be9413b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "lineSpacing":"18px",
                "location":{
                  "x":13,
                  "y":1345},
                "size":{
                  "width":285,
                  "height":162}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1ffe05657b146c683e424d5b5502949",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":1517},
            "size":{
              "width":305,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u30_line.png"}},
{
          "id":"7874488a272048b8b4418ccfd5895678",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Medium', 'Heiti SC Medium', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":12,
              "y":1534},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fbbef6ffb0c4783ada38e2ad5a5b6ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Medium', 'Heiti SC Medium', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":12,
                  "y":1534},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bce28e3e3a7045cf8024f85d7c38df49",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCC0000,
              "opacity":1},
            "location":{
              "x":63,
              "y":1531},
            "size":{
              "width":68,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8ea18de40fa4ed9b679980356b2373c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000,
                  "opacity":1},
                "location":{
                  "x":63,
                  "y":1531},
                "size":{
                  "width":68,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e9d6695c11647cca4deb0b9c9e7d301",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":12,
              "y":1554},
            "size":{
              "width":93,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54fa39e664d94f2ba22cf1f59399a3c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":12,
                  "y":1554},
                "size":{
                  "width":93,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3c5e568f00c41318464717811e2a771",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":200,
              "y":1534},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"809a2ad677ac4afaabfee97c58a0ea4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":200,
                  "y":1534},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 结算 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"结算.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u37.png"}},
{
          "id":"8cbc855b5efc4d5a946c8082f7010fb7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":907},
            "size":{
              "width":90,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u60_line.png"}},
{
          "id":"8cdb37ab0b4641da89fc07eda57607cf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":1557},
            "size":{
              "width":90,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u60_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "cfc47f7acffc4bc7abeb906cf3186d7a":{
      "scriptId":"u0"},
    "1c3c404bd03f4790826d4daa46fc34c1":{
      "scriptId":"u1"},
    "3e0f518627f34f269c3089e0e5bcfc16":{
      "scriptId":"u2"},
    "3242b5daa8f14b14936d0082ea94c8ce":{
      "scriptId":"u3"},
    "1ae22279759a48bca60aecc6461c8255":{
      "scriptId":"u4"},
    "c2d408f0d77e4d9a9f81a19d99394778":{
      "scriptId":"u5"},
    "3b3787f8e52c48e0ac23b67c146ce749":{
      "scriptId":"u6"},
    "9980d90cee614bd096c24d8ac3f26ab5":{
      "scriptId":"u7"},
    "3f55cd157a2a41b199efbc9141a95c62":{
      "scriptId":"u8"},
    "d305a70506da4c969120652473b85bf6":{
      "scriptId":"u9"},
    "5cc7351b96cf47e599b6e2d1cbb17eef":{
      "scriptId":"u10"},
    "07b53e9df51f4c90a5d823c102d99c70":{
      "scriptId":"u11"},
    "a25e910762f44e7eb5b043f551ee32e1":{
      "scriptId":"u12"},
    "14aa7831a8104b2ca88c761ad6cb3391":{
      "scriptId":"u13"},
    "645c2df6452f44db94763dc587404b63":{
      "scriptId":"u14"},
    "8362150de7694d5ba1515cc22eac2427":{
      "scriptId":"u15"},
    "7e31f52dba744371950f7736dc1d44c5":{
      "scriptId":"u16"},
    "dd29b1d518c84c53b113c5bdb3c3542d":{
      "scriptId":"u17"},
    "b77385143ba94aeebece268eac84e5b1":{
      "scriptId":"u18"},
    "57eb1ae4a76c4f4b9c78c973af103aa0":{
      "scriptId":"u19"},
    "15b8735f1e014eceb10e4f0e83b2f20a":{
      "scriptId":"u20"},
    "da9763411cc5476e8fc7804688a3811f":{
      "scriptId":"u21"},
    "c49e9f32dc6640d581a26c24532d9cf7":{
      "scriptId":"u22"},
    "8449efe5a49f442b9757657a68f22fca":{
      "scriptId":"u23"},
    "f3c8606e28054e119432a5b07edca68b":{
      "scriptId":"u24"},
    "2c27fc32c7154fc48f7354e0e946cefa":{
      "scriptId":"u25"},
    "7cb57bc65dd145e7939c558d0e344e41":{
      "scriptId":"u26"},
    "7f6bafa65a284569b59d8574fe47e40d":{
      "scriptId":"u27"},
    "74d3ed46b5644bfcb0708b2a83bd6231":{
      "scriptId":"u28"},
    "6ec11e1a14f24e33a4e38eaf3bfa592f":{
      "scriptId":"u29"},
    "854b878d27e3459387fe25e3e392013c":{
      "scriptId":"u30"},
    "280ba8153ce74b0f90ceb437be715614":{
      "scriptId":"u31"},
    "9443210395ca45a29cd9268f02c866a9":{
      "scriptId":"u32"},
    "8e2923bb345a4b11884eef2a9aee5b4e":{
      "scriptId":"u33"},
    "1e81a48cd3374891b23ac046bc751b58":{
      "scriptId":"u34"},
    "ca9c0a52f4ca433f851fa740a0e49575":{
      "scriptId":"u35"},
    "212fffaa30af4fd8893524dac4a14815":{
      "scriptId":"u36"},
    "ae9bf93e4a19462ba76f325d3e3a56dd":{
      "scriptId":"u37"},
    "b62795b912cf4979aa57a3121c8948e8":{
      "scriptId":"u38"},
    "6e26fd7ebbcd45f18ca83aafda49119a":{
      "scriptId":"u39"},
    "4a16df7f4dca45a2a3116156bfce5f0a":{
      "scriptId":"u40"},
    "5b72c6e2da0e4627870d8a0d5c5e36be":{
      "scriptId":"u41"},
    "63bc27e2203644699398871e0731834a":{
      "scriptId":"u42"},
    "0eef2249f33946e9819ffe483b0a2872":{
      "scriptId":"u43"},
    "18785ecb6e7b446fac7f03483f49cf32":{
      "scriptId":"u44"},
    "3be32eaf6581446bbc6417f32f1205e6":{
      "scriptId":"u45"},
    "a9efc2efd5cc40d28ed7c884cc70ce93":{
      "scriptId":"u46"},
    "39a423e8376c400ea6dfb6fdbd9c9bda":{
      "scriptId":"u47"},
    "18be4999036e4bb4894bfc5aa49af642":{
      "scriptId":"u48"},
    "d61897580aee4bda8bd0e19d8ea3db0f":{
      "scriptId":"u49"},
    "a0baaa14c590405f988db3b0be9413b9":{
      "scriptId":"u50"},
    "e1ffe05657b146c683e424d5b5502949":{
      "scriptId":"u51"},
    "7874488a272048b8b4418ccfd5895678":{
      "scriptId":"u52"},
    "3fbbef6ffb0c4783ada38e2ad5a5b6ff":{
      "scriptId":"u53"},
    "bce28e3e3a7045cf8024f85d7c38df49":{
      "scriptId":"u54"},
    "e8ea18de40fa4ed9b679980356b2373c":{
      "scriptId":"u55"},
    "2e9d6695c11647cca4deb0b9c9e7d301":{
      "scriptId":"u56"},
    "54fa39e664d94f2ba22cf1f59399a3c2":{
      "scriptId":"u57"},
    "a3c5e568f00c41318464717811e2a771":{
      "scriptId":"u58"},
    "809a2ad677ac4afaabfee97c58a0ea4c":{
      "scriptId":"u59"},
    "8cbc855b5efc4d5a946c8082f7010fb7":{
      "scriptId":"u60"},
    "8cdb37ab0b4641da89fc07eda57607cf":{
      "scriptId":"u61"}}});