$axure.loadCurrentPage({
  "url":"订单详情.html",
  "generationDate":new Date(1395018285598.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a701412d97fd4b64b77f43d921960099",
    "type":"Axure:Page",
    "name":"订单详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFEEEEEE},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"34a3a0d0d9784c81af92c0a2db96432f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":5,
              "y":262},
            "size":{
              "width":310,
              "height":255}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c86647c736d843e4bdcb92ea883d45c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":5,
                  "y":262},
                "size":{
                  "width":310,
                  "height":255}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详情/u0.png"}},
{
          "id":"702dc151a9f44999ad12e14b3508cee4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":285},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的订单/u4_line.png"}},
{
          "id":"142d610436f242fd8b8f3f808a468c56",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":390},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/订单详情/u3_line.png"}},
{
          "id":"3336e653317c4366a7f31893a502527a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'SimHei', 'SimHei'",
            "fontSize":"18px",
            "location":{
              "x":14,
              "y":268},
            "size":{
              "width":73,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efa3e789ab1b4659b0f7d8608508b1fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimHei', 'SimHei'",
                "fontSize":"18px",
                "location":{
                  "x":14,
                  "y":268},
                "size":{
                  "width":73,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ddc0bec2ae1470cbd2a5635944dc4ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'SimHei', 'SimHei'",
            "fontSize":"18px",
            "location":{
              "x":260,
              "y":268},
            "size":{
              "width":46,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"185e8dc9f41243fc9198c906d2537182",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimHei', 'SimHei'",
                "fontSize":"18px",
                "location":{
                  "x":260,
                  "y":268},
                "size":{
                  "width":46,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44e493e0d7fa4f2c9fae3794a789cc70",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":300},
            "size":{
              "width":86,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdafc1032d314c729442076c93b7837b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":300},
                "size":{
                  "width":86,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/结算/u24.png"}},
{
          "id":"c36670f43d764d1ebc225181fa96c0c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":111,
              "y":320},
            "size":{
              "width":185,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6de231770855425399926f29b2b80f25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":111,
                  "y":320},
                "size":{
                  "width":185,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"076e64327cc54c188b4be702c82619e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":111,
              "y":366},
            "size":{
              "width":38,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4aaece0ba3f543ee8dcb17451e8c71ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":111,
                  "y":366},
                "size":{
                  "width":38,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"565fa42d2938441291f062035316681e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":161,
              "y":369},
            "size":{
              "width":26,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a436cf053c54dec9a5fbfec0467b9ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":161,
                  "y":369},
                "size":{
                  "width":26,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c06da2bdd1fe4c38a304fc922ba1529f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":11},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d68c592dd724fa3952965de289e8acd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":11},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Back in Current Window",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/结算/u4.png"}},
{
          "id":"59b2aab117064b3aaa6e47efcc9ee95d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"18px",
            "fontWeight":"200",
            "location":{
              "x":125,
              "y":14},
            "size":{
              "width":73,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf0b02138c194c50ab8fb889cc2e45ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"18px",
                "fontWeight":"200",
                "location":{
                  "x":125,
                  "y":14},
                "size":{
                  "width":73,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ba70c7654be47b0a0df91a70275d055",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":5,
              "y":527},
            "size":{
              "width":310,
              "height":353}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca4b1a2c12a14c59b9a1acd83ff18528",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":5,
                  "y":527},
                "size":{
                  "width":310,
                  "height":353}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详情/u20.png"}},
{
          "id":"acdca54422ec43f38f02227ec5426f11",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":564},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的订单/u4_line.png"}},
{
          "id":"42b9d759ac714e7c89ff1d61879d0064",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'SimHei', 'SimHei'",
            "fontSize":"18px",
            "location":{
              "x":14,
              "y":541},
            "size":{
              "width":73,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10a41ffca08b45c69f7c76a51af97a17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimHei', 'SimHei'",
                "fontSize":"18px",
                "location":{
                  "x":14,
                  "y":541},
                "size":{
                  "width":73,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7cbce4e470343ed8416d61f8b74a143",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'SimHei', 'SimHei'",
            "fontSize":"18px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":8,
              "y":52},
            "size":{
              "width":154,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"012332a915f54779b518415dfbdfc48f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimHei', 'SimHei'",
                "fontSize":"18px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":8,
                  "y":52},
                "size":{
                  "width":154,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a4ad2010f414d6192ce158d8cd64698",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'SimHei', 'SimHei'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":237,
              "y":53},
            "size":{
              "width":73,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c81afbbf5984fe49a935d4736df0161",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimHei', 'SimHei'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":237,
                  "y":53},
                "size":{
                  "width":73,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6649ce664b0946f499aba070f80f77f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":5,
              "y":82},
            "size":{
              "width":310,
              "height":173}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99015713b9384a7ebe051cfc1520e4e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":5,
                  "y":82},
                "size":{
                  "width":310,
                  "height":173}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详情/u29.png"}},
{
          "id":"181d163fc74d42d3b1ca550bbda3e0d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'SimHei', 'SimHei'",
            "fontSize":"16px",
            "location":{
              "x":14,
              "y":154},
            "size":{
              "width":81,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6b3feb71ce144eb9649f3ccbc2f7580",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimHei', 'SimHei'",
                "fontSize":"16px",
                "location":{
                  "x":14,
                  "y":154},
                "size":{
                  "width":81,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de1ea309e91c4ee4841f886c4c00789d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "lineSpacing":"24px",
            "location":{
              "x":95,
              "y":149},
            "size":{
              "width":205,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ecb3353c2e243d1b39cbef7eb83659b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "lineSpacing":"24px",
                "location":{
                  "x":95,
                  "y":149},
                "size":{
                  "width":205,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd3292a2b9f54626921e332e84f1b5b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "lineSpacing":"24px",
            "location":{
              "x":96,
              "y":206},
            "size":{
              "width":184,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b338bcc2ff184f3dab783d8615503a5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "lineSpacing":"24px",
                "location":{
                  "x":96,
                  "y":206},
                "size":{
                  "width":184,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33c5f5b6eecc4e89ab80de2473cafeee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'SimHei', 'SimHei'",
            "fontSize":"18px",
            "location":{
              "x":36,
              "y":113},
            "size":{
              "width":55,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fb9bee4be004d56b0d81ac2328d6346",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimHei', 'SimHei'",
                "fontSize":"18px",
                "location":{
                  "x":36,
                  "y":113},
                "size":{
                  "width":55,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2b99cedf5014b0687db37c0b9209b77",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":96,
              "y":106},
            "size":{
              "width":48,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b16ae631aea849f1bcdcf7cf9f5501cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":96,
                  "y":106},
                "size":{
                  "width":48,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0699c7f9eb44bc69b0fe77b7abb5ba6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":147,
              "y":111},
            "size":{
              "width":75,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb9229e7b8074a9eaecc2e1b07b61530",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":147,
                  "y":111},
                "size":{
                  "width":75,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abfce5e276ad4325a6adbfdab39a34cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'SimHei', 'SimHei'",
            "fontSize":"16px",
            "location":{
              "x":28,
              "y":211},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47a51b47dbad471c8d440b94957cf05a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimHei', 'SimHei'",
                "fontSize":"16px",
                "location":{
                  "x":28,
                  "y":211},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b761213d316422b944fc223f882eb54",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":406},
            "size":{
              "width":86,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d4906734e054262a9857370edc9a472",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":406},
                "size":{
                  "width":86,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/结算/u24.png"}},
{
          "id":"535f29c461fc4008b14429f66b55f0b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "lineSpacing":"20px",
            "location":{
              "x":111,
              "y":422},
            "size":{
              "width":189,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcd2927d29854d34acdae60107644910",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "lineSpacing":"20px",
                "location":{
                  "x":111,
                  "y":422},
                "size":{
                  "width":189,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07dafdc613af4b549cfda50b3bb9b329",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":473},
            "size":{
              "width":38,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e08106ebc25848a696d981288aefb32a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":473},
                "size":{
                  "width":38,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78bf22c8d6bd486ba1cade0d5e7d52e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":160,
              "y":477},
            "size":{
              "width":26,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"568572a57ae549ed80ee326391fec8a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":160,
                  "y":477},
                "size":{
                  "width":26,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89cfdb736091401bafcd1698270018db",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":594},
            "size":{
              "width":10,
              "height":220},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/订单详情/u53_line.png"}},
{
          "id":"e95d6d604aeb40e28a515d12629cc1f3",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "baseStyle":"2d6526093b9d4eadb0b62a6b44451b38",
            "location":{
              "x":16,
              "y":590},
            "size":{
              "width":22,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0eb3e69200ef4e1ab890720c710e11b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"2d6526093b9d4eadb0b62a6b44451b38",
                "location":{
                  "x":16,
                  "y":590},
                "size":{
                  "width":22,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"641611f0071c40a381b27315a11c1c8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "lineSpacing":"20px",
            "location":{
              "x":38,
              "y":587},
            "size":{
              "width":232,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5973511630bf4b3381b3f2061e781fca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "lineSpacing":"20px",
                "location":{
                  "x":38,
                  "y":587},
                "size":{
                  "width":232,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c9e170d8c644c8bac28373d466ccb66",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "baseStyle":"2d6526093b9d4eadb0b62a6b44451b38",
            "location":{
              "x":15,
              "y":656},
            "size":{
              "width":22,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1b8a4533fd54410b72768af8d969a47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"2d6526093b9d4eadb0b62a6b44451b38",
                "location":{
                  "x":15,
                  "y":656},
                "size":{
                  "width":22,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"6558397d32ea427db7f878e93eaca1ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "lineSpacing":"20px",
            "location":{
              "x":37,
              "y":653},
            "size":{
              "width":232,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66c9697a43934570a4b941174a7a2f81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "lineSpacing":"20px",
                "location":{
                  "x":37,
                  "y":653},
                "size":{
                  "width":232,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bdfa74f18d36454883df57cd9043e917",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "baseStyle":"2d6526093b9d4eadb0b62a6b44451b38",
            "location":{
              "x":16,
              "y":733},
            "size":{
              "width":22,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"661f32cfc7fa458e836bcecd4d71cd67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"2d6526093b9d4eadb0b62a6b44451b38",
                "location":{
                  "x":16,
                  "y":733},
                "size":{
                  "width":22,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"20f7c603a6f44d11bf2239df097592bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "lineSpacing":"20px",
            "location":{
              "x":38,
              "y":730},
            "size":{
              "width":232,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe04d362a3ab412886d88705cafa9142",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "lineSpacing":"20px",
                "location":{
                  "x":38,
                  "y":730},
                "size":{
                  "width":232,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f39a056fc79c42d6b4ff4b990ee1f26d",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "baseStyle":"2d6526093b9d4eadb0b62a6b44451b38",
            "location":{
              "x":15,
              "y":804},
            "size":{
              "width":22,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef285db615eb4f3b8997f21880423301",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"2d6526093b9d4eadb0b62a6b44451b38",
                "location":{
                  "x":15,
                  "y":804},
                "size":{
                  "width":22,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"a3c3ceec0f714879b8d94cb3e784ef20",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "lineSpacing":"20px",
            "location":{
              "x":37,
              "y":801},
            "size":{
              "width":232,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8122b93ef49d4e78a9c3ae354dbfa4fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "lineSpacing":"20px",
                "location":{
                  "x":37,
                  "y":801},
                "size":{
                  "width":232,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "34a3a0d0d9784c81af92c0a2db96432f":{
      "scriptId":"u0"},
    "c86647c736d843e4bdcb92ea883d45c5":{
      "scriptId":"u1"},
    "702dc151a9f44999ad12e14b3508cee4":{
      "scriptId":"u2"},
    "142d610436f242fd8b8f3f808a468c56":{
      "scriptId":"u3"},
    "3336e653317c4366a7f31893a502527a":{
      "scriptId":"u4"},
    "efa3e789ab1b4659b0f7d8608508b1fe":{
      "scriptId":"u5"},
    "0ddc0bec2ae1470cbd2a5635944dc4ad":{
      "scriptId":"u6"},
    "185e8dc9f41243fc9198c906d2537182":{
      "scriptId":"u7"},
    "44e493e0d7fa4f2c9fae3794a789cc70":{
      "scriptId":"u8"},
    "bdafc1032d314c729442076c93b7837b":{
      "scriptId":"u9"},
    "c36670f43d764d1ebc225181fa96c0c0":{
      "scriptId":"u10"},
    "6de231770855425399926f29b2b80f25":{
      "scriptId":"u11"},
    "076e64327cc54c188b4be702c82619e3":{
      "scriptId":"u12"},
    "4aaece0ba3f543ee8dcb17451e8c71ce":{
      "scriptId":"u13"},
    "565fa42d2938441291f062035316681e":{
      "scriptId":"u14"},
    "0a436cf053c54dec9a5fbfec0467b9ba":{
      "scriptId":"u15"},
    "c06da2bdd1fe4c38a304fc922ba1529f":{
      "scriptId":"u16"},
    "6d68c592dd724fa3952965de289e8acd":{
      "scriptId":"u17"},
    "59b2aab117064b3aaa6e47efcc9ee95d":{
      "scriptId":"u18"},
    "bf0b02138c194c50ab8fb889cc2e45ac":{
      "scriptId":"u19"},
    "9ba70c7654be47b0a0df91a70275d055":{
      "scriptId":"u20"},
    "ca4b1a2c12a14c59b9a1acd83ff18528":{
      "scriptId":"u21"},
    "acdca54422ec43f38f02227ec5426f11":{
      "scriptId":"u22"},
    "42b9d759ac714e7c89ff1d61879d0064":{
      "scriptId":"u23"},
    "10a41ffca08b45c69f7c76a51af97a17":{
      "scriptId":"u24"},
    "f7cbce4e470343ed8416d61f8b74a143":{
      "scriptId":"u25"},
    "012332a915f54779b518415dfbdfc48f":{
      "scriptId":"u26"},
    "3a4ad2010f414d6192ce158d8cd64698":{
      "scriptId":"u27"},
    "3c81afbbf5984fe49a935d4736df0161":{
      "scriptId":"u28"},
    "6649ce664b0946f499aba070f80f77f5":{
      "scriptId":"u29"},
    "99015713b9384a7ebe051cfc1520e4e6":{
      "scriptId":"u30"},
    "181d163fc74d42d3b1ca550bbda3e0d5":{
      "scriptId":"u31"},
    "a6b3feb71ce144eb9649f3ccbc2f7580":{
      "scriptId":"u32"},
    "de1ea309e91c4ee4841f886c4c00789d":{
      "scriptId":"u33"},
    "8ecb3353c2e243d1b39cbef7eb83659b":{
      "scriptId":"u34"},
    "fd3292a2b9f54626921e332e84f1b5b2":{
      "scriptId":"u35"},
    "b338bcc2ff184f3dab783d8615503a5a":{
      "scriptId":"u36"},
    "33c5f5b6eecc4e89ab80de2473cafeee":{
      "scriptId":"u37"},
    "0fb9bee4be004d56b0d81ac2328d6346":{
      "scriptId":"u38"},
    "b2b99cedf5014b0687db37c0b9209b77":{
      "scriptId":"u39"},
    "b16ae631aea849f1bcdcf7cf9f5501cf":{
      "scriptId":"u40"},
    "a0699c7f9eb44bc69b0fe77b7abb5ba6":{
      "scriptId":"u41"},
    "cb9229e7b8074a9eaecc2e1b07b61530":{
      "scriptId":"u42"},
    "abfce5e276ad4325a6adbfdab39a34cf":{
      "scriptId":"u43"},
    "47a51b47dbad471c8d440b94957cf05a":{
      "scriptId":"u44"},
    "3b761213d316422b944fc223f882eb54":{
      "scriptId":"u45"},
    "9d4906734e054262a9857370edc9a472":{
      "scriptId":"u46"},
    "535f29c461fc4008b14429f66b55f0b4":{
      "scriptId":"u47"},
    "bcd2927d29854d34acdae60107644910":{
      "scriptId":"u48"},
    "07dafdc613af4b549cfda50b3bb9b329":{
      "scriptId":"u49"},
    "e08106ebc25848a696d981288aefb32a":{
      "scriptId":"u50"},
    "78bf22c8d6bd486ba1cade0d5e7d52e3":{
      "scriptId":"u51"},
    "568572a57ae549ed80ee326391fec8a5":{
      "scriptId":"u52"},
    "89cfdb736091401bafcd1698270018db":{
      "scriptId":"u53"},
    "e95d6d604aeb40e28a515d12629cc1f3":{
      "scriptId":"u54"},
    "0eb3e69200ef4e1ab890720c710e11b5":{
      "scriptId":"u55"},
    "641611f0071c40a381b27315a11c1c8c":{
      "scriptId":"u56"},
    "5973511630bf4b3381b3f2061e781fca":{
      "scriptId":"u57"},
    "5c9e170d8c644c8bac28373d466ccb66":{
      "scriptId":"u58"},
    "d1b8a4533fd54410b72768af8d969a47":{
      "scriptId":"u59"},
    "6558397d32ea427db7f878e93eaca1ac":{
      "scriptId":"u60"},
    "66c9697a43934570a4b941174a7a2f81":{
      "scriptId":"u61"},
    "bdfa74f18d36454883df57cd9043e917":{
      "scriptId":"u62"},
    "661f32cfc7fa458e836bcecd4d71cd67":{
      "scriptId":"u63"},
    "20f7c603a6f44d11bf2239df097592bd":{
      "scriptId":"u64"},
    "fe04d362a3ab412886d88705cafa9142":{
      "scriptId":"u65"},
    "f39a056fc79c42d6b4ff4b990ee1f26d":{
      "scriptId":"u66"},
    "ef285db615eb4f3b8997f21880423301":{
      "scriptId":"u67"},
    "a3c3ceec0f714879b8d94cb3e784ef20":{
      "scriptId":"u68"},
    "8122b93ef49d4e78a9c3ae354dbfa4fd":{
      "scriptId":"u69"}}});