$axure.loadCurrentPage({
  "url":"搜索.html",
  "generationDate":new Date(1395018284838.61),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"31965e02e7dd48908d043bea6e6ef400",
    "type":"Axure:Page",
    "name":"搜索",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFEEEEEE},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"876957d7976240629ee3934dec869d48",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":0},
            "size":{
              "width":315,
              "height":315},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c150735e0a241e7aed4c6c217c55e9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":0},
                "size":{
                  "width":315,
                  "height":315},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"f581eacad09c490fb6ccc0d628149767",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":6,
              "y":313},
            "size":{
              "width":315,
              "height":327},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3991ae79f8264d398d7c504e3e57511d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":6,
                  "y":313},
                "size":{
                  "width":315,
                  "height":327},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"d9b3adc57cf8452985517f38d7c9980e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":6},
            "size":{
              "width":300,
              "height":300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2c131acaaaf49e99e4b647b8e4d48dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":6},
                "size":{
                  "width":300,
                  "height":300}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 商品详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"商品详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u22.jpg"}},
{
          "id":"245b1dd2cdb14b48850f924c12ec6a2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"18px",
            "fontWeight":"200",
            "location":{
              "x":15,
              "y":325},
            "size":{
              "width":285,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e42c70b7ed4944e8bc340eef10a3cb95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"18px",
                "fontWeight":"200",
                "location":{
                  "x":15,
                  "y":325},
                "size":{
                  "width":285,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 商品详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"商品详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dddd4e8739f74463b9feab49f5d3f4ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":15,
              "y":354},
            "size":{
              "width":277,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ff0b2deb36543b4824ff84b272f96a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":15,
                  "y":354},
                "size":{
                  "width":277,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1385b397ceb741f5a0b08b418de7f353",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "lineSpacing":"18px",
            "location":{
              "x":13,
              "y":403},
            "size":{
              "width":285,
              "height":162}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f03f0f22e5d2407fafad69b40aa6892f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "lineSpacing":"18px",
                "location":{
                  "x":13,
                  "y":403},
                "size":{
                  "width":285,
                  "height":162}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f63ea4e6936b42e6b9a8aaafc3fadaa4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":575},
            "size":{
              "width":305,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u30_line.png"}},
{
          "id":"90ca92b4c0df4830873050014c081b20",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Medium', 'Heiti SC Medium', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":12,
              "y":592},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87afb4b6a9394662b621279ef9cf3f33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Medium', 'Heiti SC Medium', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":12,
                  "y":592},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8de6704b248d4387b812cd6b7fe47061",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCC0000,
              "opacity":1},
            "location":{
              "x":63,
              "y":589},
            "size":{
              "width":68,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95262eb943664ce2a3d4a39492ab26eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000,
                  "opacity":1},
                "location":{
                  "x":63,
                  "y":589},
                "size":{
                  "width":68,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86e72c7e7f2d455ba90a25daf34d10bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":12,
              "y":612},
            "size":{
              "width":93,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49822fbc7f6443bca4f31b729595c556",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":12,
                  "y":612},
                "size":{
                  "width":93,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"384c33c3b1674b778270fcdca2b6cf21",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":200,
              "y":592},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54a371754221409686975a91d3695ec6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":200,
                  "y":592},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 结算 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"结算.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u37.png"}},
{
          "id":"0fe87ad61a0c4191bfd77a00c326e4d7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":615},
            "size":{
              "width":90,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u60_line.png"}},
{
          "id":"4f0310e4fb674f1797725649d8f23df8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":650},
            "size":{
              "width":315,
              "height":315},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f0a07f5951c4f3fa6301997fa7f3159",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":650},
                "size":{
                  "width":315,
                  "height":315},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"93d08e91b95f43c195ba709b5f97b4cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":6,
              "y":963},
            "size":{
              "width":315,
              "height":327},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b284c35fadb4e849eaf53d2e2adb0b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":6,
                  "y":963},
                "size":{
                  "width":315,
                  "height":327},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"f7d9175ca26841108d764f03e574157b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":656},
            "size":{
              "width":300,
              "height":300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0115b229bfd54fc09b2e50f56e1332ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":656},
                "size":{
                  "width":300,
                  "height":300}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 商品详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"商品详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u22.jpg"}},
{
          "id":"b7e6c1b8d6a9415f8d9b84ee625f1322",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"18px",
            "fontWeight":"200",
            "location":{
              "x":15,
              "y":975},
            "size":{
              "width":285,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"047093e5737f4a3aa4b8ea7f1ea99a76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"18px",
                "fontWeight":"200",
                "location":{
                  "x":15,
                  "y":975},
                "size":{
                  "width":285,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 商品详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"商品详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"909b820e0f7f4fabb4787e42c9f50595",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":15,
              "y":1004},
            "size":{
              "width":277,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"898016acf4e449519d86073fb3b0d78e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":15,
                  "y":1004},
                "size":{
                  "width":277,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7131094cb0ed470c953b6fa1015d08a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "lineSpacing":"18px",
            "location":{
              "x":13,
              "y":1053},
            "size":{
              "width":285,
              "height":162}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98fee755074b450281d6ff20bdcfea3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "lineSpacing":"18px",
                "location":{
                  "x":13,
                  "y":1053},
                "size":{
                  "width":285,
                  "height":162}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb6c4270b7954c1e8da8512b51b8aa24",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":1225},
            "size":{
              "width":305,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u30_line.png"}},
{
          "id":"60ad998339784a1da77da248b025bcf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Medium', 'Heiti SC Medium', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":12,
              "y":1242},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3361e34f140543d89b992d250bca636e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Medium', 'Heiti SC Medium', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":12,
                  "y":1242},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1d2b70986974e149b9062007941ec79",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCC0000,
              "opacity":1},
            "location":{
              "x":63,
              "y":1239},
            "size":{
              "width":68,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4065a58a8d23494cb10774cf6bb93648",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000,
                  "opacity":1},
                "location":{
                  "x":63,
                  "y":1239},
                "size":{
                  "width":68,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"666a5ebe79f64efc8a0c4c3d93f8abc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":12,
              "y":1262},
            "size":{
              "width":93,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54f6c63281b142b1a5c6a18b238a9ef9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":12,
                  "y":1262},
                "size":{
                  "width":93,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c8a0ca01c9d4d2cb98249aca64f5d57",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":200,
              "y":1242},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5dc198bb50a4eed99380fc1da079f8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":200,
                  "y":1242},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 结算 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"结算.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u37.png"}},
{
          "id":"a8974e8733d7498cb39cd655abf46881",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":1265},
            "size":{
              "width":90,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u60_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "876957d7976240629ee3934dec869d48":{
      "scriptId":"u0"},
    "1c150735e0a241e7aed4c6c217c55e9f":{
      "scriptId":"u1"},
    "f581eacad09c490fb6ccc0d628149767":{
      "scriptId":"u2"},
    "3991ae79f8264d398d7c504e3e57511d":{
      "scriptId":"u3"},
    "d9b3adc57cf8452985517f38d7c9980e":{
      "scriptId":"u4"},
    "d2c131acaaaf49e99e4b647b8e4d48dd":{
      "scriptId":"u5"},
    "245b1dd2cdb14b48850f924c12ec6a2f":{
      "scriptId":"u6"},
    "e42c70b7ed4944e8bc340eef10a3cb95":{
      "scriptId":"u7"},
    "dddd4e8739f74463b9feab49f5d3f4ee":{
      "scriptId":"u8"},
    "3ff0b2deb36543b4824ff84b272f96a1":{
      "scriptId":"u9"},
    "1385b397ceb741f5a0b08b418de7f353":{
      "scriptId":"u10"},
    "f03f0f22e5d2407fafad69b40aa6892f":{
      "scriptId":"u11"},
    "f63ea4e6936b42e6b9a8aaafc3fadaa4":{
      "scriptId":"u12"},
    "90ca92b4c0df4830873050014c081b20":{
      "scriptId":"u13"},
    "87afb4b6a9394662b621279ef9cf3f33":{
      "scriptId":"u14"},
    "8de6704b248d4387b812cd6b7fe47061":{
      "scriptId":"u15"},
    "95262eb943664ce2a3d4a39492ab26eb":{
      "scriptId":"u16"},
    "86e72c7e7f2d455ba90a25daf34d10bc":{
      "scriptId":"u17"},
    "49822fbc7f6443bca4f31b729595c556":{
      "scriptId":"u18"},
    "384c33c3b1674b778270fcdca2b6cf21":{
      "scriptId":"u19"},
    "54a371754221409686975a91d3695ec6":{
      "scriptId":"u20"},
    "0fe87ad61a0c4191bfd77a00c326e4d7":{
      "scriptId":"u21"},
    "4f0310e4fb674f1797725649d8f23df8":{
      "scriptId":"u22"},
    "9f0a07f5951c4f3fa6301997fa7f3159":{
      "scriptId":"u23"},
    "93d08e91b95f43c195ba709b5f97b4cd":{
      "scriptId":"u24"},
    "0b284c35fadb4e849eaf53d2e2adb0b7":{
      "scriptId":"u25"},
    "f7d9175ca26841108d764f03e574157b":{
      "scriptId":"u26"},
    "0115b229bfd54fc09b2e50f56e1332ed":{
      "scriptId":"u27"},
    "b7e6c1b8d6a9415f8d9b84ee625f1322":{
      "scriptId":"u28"},
    "047093e5737f4a3aa4b8ea7f1ea99a76":{
      "scriptId":"u29"},
    "909b820e0f7f4fabb4787e42c9f50595":{
      "scriptId":"u30"},
    "898016acf4e449519d86073fb3b0d78e":{
      "scriptId":"u31"},
    "7131094cb0ed470c953b6fa1015d08a3":{
      "scriptId":"u32"},
    "98fee755074b450281d6ff20bdcfea3f":{
      "scriptId":"u33"},
    "fb6c4270b7954c1e8da8512b51b8aa24":{
      "scriptId":"u34"},
    "60ad998339784a1da77da248b025bcf2":{
      "scriptId":"u35"},
    "3361e34f140543d89b992d250bca636e":{
      "scriptId":"u36"},
    "c1d2b70986974e149b9062007941ec79":{
      "scriptId":"u37"},
    "4065a58a8d23494cb10774cf6bb93648":{
      "scriptId":"u38"},
    "666a5ebe79f64efc8a0c4c3d93f8abc5":{
      "scriptId":"u39"},
    "54f6c63281b142b1a5c6a18b238a9ef9":{
      "scriptId":"u40"},
    "4c8a0ca01c9d4d2cb98249aca64f5d57":{
      "scriptId":"u41"},
    "d5dc198bb50a4eed99380fc1da079f8c":{
      "scriptId":"u42"},
    "a8974e8733d7498cb39cd655abf46881":{
      "scriptId":"u43"}}});