$axure.loadCurrentPage({
  "url":"菲生活微商城.html",
  "generationDate":new Date(1395018284402.28),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ffec7e3a91ce4097a047f60237f660de",
    "type":"Axure:Page",
    "name":"菲生活微商城",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d78461b16fd34c34aef70d8b4f3c4b17",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":2,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"65ba16631fff4b5fb36b5fe59054b10f"},
{
          "id":"200634faa1a543869f765b4e36b9cb65",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":-1,
              "y":40},
            "size":{
              "width":320,
              "height":420}},
          "adaptiveStyles":{
},
          "target":{
            "targetType":"page",
            "url":"首页.html",
            "includeVariables":true}},
{
          "id":"9e08af96647c4e9a831c93a63d3b1ae9",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":24,
              "height":24}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"Open 首页 in (Inline Frame)",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["200634faa1a543869f765b4e36b9cb65"],
                          "target":{
                            "targetType":"page",
                            "url":"首页.html",
                            "includeVariables":true}}]},
{
                      "action":"setPanelState",
                      "description":"Set title to State1,<br>布局/(Dynamic Panel) to State1",
                      "panelsToStates":[{
                          "panelPath":["1541fd29ae864caca2fee9aaa07d23d5"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}},
{
                          "panelPath":["d78461b16fd34c34aef70d8b4f3c4b17",
"e28ec566dd7d45c4a112361268936e61"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true},
{
          "id":"da8279517a014bfb99617b502d2b80ab",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":286,
              "y":10},
            "size":{
              "width":24,
              "height":24}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"Open 搜索 in (Inline Frame)",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["200634faa1a543869f765b4e36b9cb65"],
                          "target":{
                            "targetType":"page",
                            "url":"搜索.html",
                            "includeVariables":true}}]},
{
                      "action":"setPanelState",
                      "description":"Set 布局/(Dynamic Panel) to State2,<br>title to State5",
                      "panelsToStates":[{
                          "panelPath":["d78461b16fd34c34aef70d8b4f3c4b17",
"e28ec566dd7d45c4a112361268936e61"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}},
{
                          "panelPath":["1541fd29ae864caca2fee9aaa07d23d5"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":5,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true},
{
          "id":"da025864082c480aa6c464ce578f60db",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":10},
            "size":{
              "width":24,
              "height":24}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"Open 我的订单 in (Inline Frame)",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["200634faa1a543869f765b4e36b9cb65"],
                          "target":{
                            "targetType":"page",
                            "url":"我的订单.html",
                            "includeVariables":true}}]},
{
                      "action":"setPanelState",
                      "description":"Set title to State2",
                      "panelsToStates":[{
                          "panelPath":["1541fd29ae864caca2fee9aaa07d23d5"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true},
{
          "id":"1541fd29ae864caca2fee9aaa07d23d5",
          "label":"title",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":12},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"8a6193c1b7754096be6dc25b45a3d109",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"386feee0e65644dfbd0435c49a47d636",
                  "label":"",
                  "parentDynamicPanel":"1541fd29ae864caca2fee9aaa07d23d5",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'SimHei', 'SimHei'",
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF309AF1,
                      "opacity":1},
                    "size":{
                      "width":73,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"800b1e9df6d546468ca52facc59331da",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1541fd29ae864caca2fee9aaa07d23d5",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'SimHei', 'SimHei'",
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF309AF1,
                          "opacity":1},
                        "size":{
                          "width":73,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"d28e121ec38f4afd8abe2895a9dcd879",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"093a3125f3884146836690ab444e9712",
                  "label":"",
                  "parentDynamicPanel":"1541fd29ae864caca2fee9aaa07d23d5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'SimHei', 'SimHei'",
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF309AF1,
                      "opacity":1},
                    "size":{
                      "width":73,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c1f47b9fb46540bc8a6e8106ea7d401a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1541fd29ae864caca2fee9aaa07d23d5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'SimHei', 'SimHei'",
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF309AF1,
                          "opacity":1},
                        "size":{
                          "width":73,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"b42fbb920e1746b3aa121dd6b4b52b4f",
              "label":"State4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ea23d050e28f4e8280ed90e7c72b3f02",
                  "label":"",
                  "parentDynamicPanel":"1541fd29ae864caca2fee9aaa07d23d5",
                  "panelIndex":2,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'SimHei', 'SimHei'",
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF309AF1,
                      "opacity":1},
                    "size":{
                      "width":73,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d43ccfc8bc4b4fd7bc8bd878dcbc4008",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1541fd29ae864caca2fee9aaa07d23d5",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'SimHei', 'SimHei'",
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF309AF1,
                          "opacity":1},
                        "size":{
                          "width":73,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"74f7a42059824a6e85d86fce94548b46",
              "label":"State3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"474fce5814fe47cb9718e70ccb8bc9c3",
                  "label":"",
                  "parentDynamicPanel":"1541fd29ae864caca2fee9aaa07d23d5",
                  "panelIndex":3,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'SimHei', 'SimHei'",
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF309AF1,
                      "opacity":1},
                    "size":{
                      "width":73,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0cb5a9042b504147b08616dd4e87f674",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1541fd29ae864caca2fee9aaa07d23d5",
                      "panelIndex":3,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'SimHei', 'SimHei'",
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF309AF1,
                          "opacity":1},
                        "size":{
                          "width":73,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"280dcf6065114abe8f25e144da56cdca",
              "label":"State5",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "65ba16631fff4b5fb36b5fe59054b10f":{
      "packageId":"65ba16631fff4b5fb36b5fe59054b10f",
      "type":"Axure:Master",
      "name":"布局",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"e28ec566dd7d45c4a112361268936e61",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":1,
                "y":0},
              "size":{
                "width":10,
                "height":10}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"b2ea3d10c10247c6a6130ded62ce5f26",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"125869b4d78a4a1bb8721228526fb402",
                    "label":"",
                    "parentDynamicPanel":"e28ec566dd7d45c4a112361268936e61",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":318,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFF999999}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2bb164eafd8945cba8891bb96c79c167",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"e28ec566dd7d45c4a112361268936e61",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":318,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFF999999}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/菲生活微商城/u2.png"}},
{
                    "id":"5b8c6f58ebb14b3283040553439085c2",
                    "label":"",
                    "parentDynamicPanel":"e28ec566dd7d45c4a112361268936e61",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":10,
                        "y":7.5},
                      "size":{
                        "width":25,
                        "height":25},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFF000000}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8c81c8240e304162ad4e4512a7982e39",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"e28ec566dd7d45c4a112361268936e61",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":10,
                            "y":7.5},
                          "size":{
                            "width":25,
                            "height":25},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFF000000}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/菲生活微商城/u4.png"}},
{
                    "id":"178c8370546d4bbb8b14d85ff574e58e",
                    "label":"",
                    "parentDynamicPanel":"e28ec566dd7d45c4a112361268936e61",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":256,
                        "y":9},
                      "size":{
                        "width":24,
                        "height":24},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFF000000}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"7ee799bf35454795b1defcfe937f8619",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"e28ec566dd7d45c4a112361268936e61",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":256,
                            "y":9},
                          "size":{
                            "width":24,
                            "height":24},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFF000000}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/菲生活微商城/u6.png"}},
{
                    "id":"f1592689c5464f87b876bdfc49202096",
                    "label":"",
                    "parentDynamicPanel":"e28ec566dd7d45c4a112361268936e61",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":287,
                        "y":10},
                      "size":{
                        "width":23,
                        "height":23},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFF000000}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"3f3bc741b9304939a9229900ce83046b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"e28ec566dd7d45c4a112361268936e61",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":287,
                            "y":10},
                          "size":{
                            "width":23,
                            "height":23},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFF000000}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"Set (Dynamic Panel) to State2",
                                "panelsToStates":[{
                                    "panelPath":["e28ec566dd7d45c4a112361268936e61"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":2,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/菲生活微商城/u8.png"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}},
{
                "id":"4b358512977345ae9327ede8caed9ad6",
                "label":"State2",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"4fb044a1f4d84de1b581fa9648a2380e",
                    "label":"",
                    "parentDynamicPanel":"e28ec566dd7d45c4a112361268936e61",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":1,
                        "y":0},
                      "size":{
                        "width":318,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFF999999}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2067d84adb2a41409dce4f152144e38b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"e28ec566dd7d45c4a112361268936e61",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":1,
                            "y":0},
                          "size":{
                            "width":318,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFF999999}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/菲生活微商城/u2.png"}},
{
                    "id":"ccd8679d2cdd44fd88eadc633aa4971f",
                    "label":"",
                    "parentDynamicPanel":"e28ec566dd7d45c4a112361268936e61",
                    "panelIndex":1,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":11,
                        "y":8},
                      "size":{
                        "width":25,
                        "height":25},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFF000000}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"b05c6bcfe403462486b7a9ecc7e9344d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"e28ec566dd7d45c4a112361268936e61",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":11,
                            "y":8},
                          "size":{
                            "width":25,
                            "height":25},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFF000000}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/菲生活微商城/u4.png"}},
{
                    "id":"4d73e88035b84d48a9414986b95405ef",
                    "label":"",
                    "parentDynamicPanel":"e28ec566dd7d45c4a112361268936e61",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":71,
                        "y":5},
                      "size":{
                        "width":208,
                        "height":30},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFF379CF2}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8be00620bc764be8a06d573742c4887c",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"e28ec566dd7d45c4a112361268936e61",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":71,
                            "y":5},
                          "size":{
                            "width":208,
                            "height":30},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFF379CF2}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/菲生活微商城/u14.png"}},
{
                    "id":"33ac87c1e19d49ef98c381be57d64c78",
                    "label":"",
                    "parentDynamicPanel":"e28ec566dd7d45c4a112361268936e61",
                    "panelIndex":1,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":288,
                        "y":10},
                      "size":{
                        "width":23,
                        "height":23},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFF000000}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"cc84194d76224ffe9c637bbb3e4f1099",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"e28ec566dd7d45c4a112361268936e61",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":288,
                            "y":10},
                          "size":{
                            "width":23,
                            "height":23},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFF000000}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/菲生活微商城/u8.png"}},
{
                    "id":"53cd669e607349189a60954171fab49f",
                    "label":"",
                    "parentDynamicPanel":"e28ec566dd7d45c4a112361268936e61",
                    "panelIndex":1,
                    "type":"flowShape",
                    "styleType":"flowShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF},
                      "location":{
                        "x":44,
                        "y":10},
                      "size":{
                        "width":31,
                        "height":21},
                      "rotation":"90",
                      "textRotation":"90",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFF2B98FB}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a3fd979695414999a114c9acb1ce0e71",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"e28ec566dd7d45c4a112361268936e61",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF},
                          "location":{
                            "x":44,
                            "y":10},
                          "size":{
                            "width":31,
                            "height":21},
                          "rotation":"90",
                          "textRotation":"90",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFF2B98FB}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"Set (Dynamic Panel) to State1",
                                "panelsToStates":[{
                                    "panelPath":["e28ec566dd7d45c4a112361268936e61"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":1,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/菲生活微商城/u18.png"}},
{
                    "id":"720576a9439647208d5bf0320be3bfad",
                    "label":"",
                    "parentDynamicPanel":"e28ec566dd7d45c4a112361268936e61",
                    "panelIndex":1,
                    "type":"textBox",
                    "styleType":"textBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":73,
                        "y":7},
                      "size":{
                        "width":204,
                        "height":25}},
                    "adaptiveStyles":{
}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"d2c8bb6e1dab4bd6b36207d566ba17ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":286,
                "y":4},
              "size":{
                "width":25,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"98544d46c25b4eef923f5d448c4aee7a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":286,
                    "y":4},
                  "size":{
                    "width":25,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setPanelState",
                        "description":"Set (Dynamic Panel) to State2",
                        "panelsToStates":[{
                            "panelPath":["e28ec566dd7d45c4a112361268936e61"],
                            "stateInfo":{
                              "setStateType":"diagram",
                              "stateNumber":2,
                              "stateValue":{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]},
                              "loop":false,
                              "showWhenSet":false,
                              "options":{
                                "compress":false}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "d78461b16fd34c34aef70d8b4f3c4b17":{
      "scriptId":"u0",
      "e28ec566dd7d45c4a112361268936e61":{
        "scriptId":"u1"},
      "125869b4d78a4a1bb8721228526fb402":{
        "scriptId":"u2"},
      "2bb164eafd8945cba8891bb96c79c167":{
        "scriptId":"u3"},
      "5b8c6f58ebb14b3283040553439085c2":{
        "scriptId":"u4"},
      "8c81c8240e304162ad4e4512a7982e39":{
        "scriptId":"u5"},
      "178c8370546d4bbb8b14d85ff574e58e":{
        "scriptId":"u6"},
      "7ee799bf35454795b1defcfe937f8619":{
        "scriptId":"u7"},
      "f1592689c5464f87b876bdfc49202096":{
        "scriptId":"u8"},
      "3f3bc741b9304939a9229900ce83046b":{
        "scriptId":"u9"},
      "4fb044a1f4d84de1b581fa9648a2380e":{
        "scriptId":"u10"},
      "2067d84adb2a41409dce4f152144e38b":{
        "scriptId":"u11"},
      "ccd8679d2cdd44fd88eadc633aa4971f":{
        "scriptId":"u12"},
      "b05c6bcfe403462486b7a9ecc7e9344d":{
        "scriptId":"u13"},
      "4d73e88035b84d48a9414986b95405ef":{
        "scriptId":"u14"},
      "8be00620bc764be8a06d573742c4887c":{
        "scriptId":"u15"},
      "33ac87c1e19d49ef98c381be57d64c78":{
        "scriptId":"u16"},
      "cc84194d76224ffe9c637bbb3e4f1099":{
        "scriptId":"u17"},
      "53cd669e607349189a60954171fab49f":{
        "scriptId":"u18"},
      "a3fd979695414999a114c9acb1ce0e71":{
        "scriptId":"u19"},
      "720576a9439647208d5bf0320be3bfad":{
        "scriptId":"u20"},
      "d2c8bb6e1dab4bd6b36207d566ba17ea":{
        "scriptId":"u21"},
      "98544d46c25b4eef923f5d448c4aee7a":{
        "scriptId":"u22"}},
    "200634faa1a543869f765b4e36b9cb65":{
      "scriptId":"u23"},
    "9e08af96647c4e9a831c93a63d3b1ae9":{
      "scriptId":"u24"},
    "da8279517a014bfb99617b502d2b80ab":{
      "scriptId":"u25"},
    "da025864082c480aa6c464ce578f60db":{
      "scriptId":"u26"},
    "1541fd29ae864caca2fee9aaa07d23d5":{
      "scriptId":"u27"},
    "386feee0e65644dfbd0435c49a47d636":{
      "scriptId":"u28"},
    "800b1e9df6d546468ca52facc59331da":{
      "scriptId":"u29"},
    "093a3125f3884146836690ab444e9712":{
      "scriptId":"u30"},
    "c1f47b9fb46540bc8a6e8106ea7d401a":{
      "scriptId":"u31"},
    "ea23d050e28f4e8280ed90e7c72b3f02":{
      "scriptId":"u32"},
    "d43ccfc8bc4b4fd7bc8bd878dcbc4008":{
      "scriptId":"u33"},
    "474fce5814fe47cb9718e70ccb8bc9c3":{
      "scriptId":"u34"},
    "0cb5a9042b504147b08616dd4e87f674":{
      "scriptId":"u35"}}});
