$axure.loadCurrentPage({
  "url":"结算.html",
  "generationDate":new Date(1395018285107.16),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"47cbb65820f24a47942ab182c54197ba",
    "type":"Axure:Page",
    "name":"结算",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFEEEEEE},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fd3e78ffd9ea418592c5002e0d8f7bd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":5,
              "y":172},
            "size":{
              "width":310,
              "height":115}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ef3a042aef549d9899552d6fbc24c0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":5,
                  "y":172},
                "size":{
                  "width":310,
                  "height":115}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/结算/u0.png"}},
{
          "id":"1686b5a58bdc4beab0cd36f51dc17606",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'SimHei', 'SimHei'",
            "fontSize":"18px",
            "location":{
              "x":14,
              "y":196},
            "size":{
              "width":55,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e1d4d395770453ba5a0e13b63f519b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimHei', 'SimHei'",
                "fontSize":"18px",
                "location":{
                  "x":14,
                  "y":196},
                "size":{
                  "width":55,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c789bc7caf9e4a11ac558cb1265eea00",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":11},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbf234ebe3a042499a76469ef40ab627",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":11},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/结算/u4.png"}},
{
          "id":"ef19eaca1f014c7796f91c8e2d9a5462",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"18px",
            "fontWeight":"200",
            "location":{
              "x":125,
              "y":14},
            "size":{
              "width":73,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7da4226250c4a678b8ed2df46606acf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"18px",
                "fontWeight":"200",
                "location":{
                  "x":125,
                  "y":14},
                "size":{
                  "width":73,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8781bcccf4d4f34b08414611b7dd6fb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":291,
              "y":215},
            "size":{
              "width":17,
              "height":10},
            "rotation":"45",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 收货地址 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"收货地址.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/结算/u8_line.png"}},
{
          "id":"b227654ca9024c4a9af37d73ca01affa",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":291,
              "y":225},
            "size":{
              "width":17,
              "height":10},
            "rotation":"135",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 收货地址 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"收货地址.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/结算/u8_line.png"}},
{
          "id":"d5b55ab1b54b407085c76bf8f6c64f36",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "lineSpacing":"24px",
            "location":{
              "x":63,
              "y":192},
            "size":{
              "width":205,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcb0f033a3bd46afabc694c16ddd1ec6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "lineSpacing":"24px",
                "location":{
                  "x":63,
                  "y":192},
                "size":{
                  "width":205,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dda341141a75436da8d395b0fbcf48e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "lineSpacing":"24px",
            "location":{
              "x":60,
              "y":250},
            "size":{
              "width":184,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33992f34062e48e9ae5a83207d3e5330",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "lineSpacing":"24px",
                "location":{
                  "x":60,
                  "y":250},
                "size":{
                  "width":184,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40824ffd911b4ffa8e13f4cf5c5e2cb9",
          "label":"ButtonBigSecondary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"24px",
            "fontWeight":"400",
            "baseStyle":"e327ff603fa44748ad8b15dc502bb678",
            "stateStyles":{
              "mouseDown":{
                "baseStyle":"2d6526093b9d4eadb0b62a6b44451b38"}},
            "location":{
              "x":5,
              "y":307},
            "size":{
              "width":310,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff22300590314a38aa6e08de7e912e5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"24px",
                "fontWeight":"400",
                "baseStyle":"e327ff603fa44748ad8b15dc502bb678",
                "stateStyles":{
                  "mouseDown":{
                    "baseStyle":"2d6526093b9d4eadb0b62a6b44451b38"}},
                "location":{
                  "x":5,
                  "y":307},
                "size":{
                  "width":310,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 支付 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"支付.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/结算/buttonbigsecondary_u14.png",
            "mouseDown~":"images/结算/buttonbigsecondary_u14_mouseDown.png"}},
{
          "id":"61f26f6c556a445a9b8df416ae193e4c",
          "label":"ButtonBigSecondary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun-ExtB', 'SimSun-ExtB'",
            "fontSize":"24px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "baseStyle":"e327ff603fa44748ad8b15dc502bb678",
            "stateStyles":{
              "mouseDown":{
                "baseStyle":"2d6526093b9d4eadb0b62a6b44451b38"}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":5,
              "y":367},
            "size":{
              "width":310,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bea06d0273245eeae935fd706ffe5ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun-ExtB', 'SimSun-ExtB'",
                "fontSize":"24px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "baseStyle":"e327ff603fa44748ad8b15dc502bb678",
                "stateStyles":{
                  "mouseDown":{
                    "baseStyle":"2d6526093b9d4eadb0b62a6b44451b38"}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":5,
                  "y":367},
                "size":{
                  "width":310,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 订单详情 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"订单详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/结算/buttonbigsecondary_u16.png",
            "mouseDown~":"images/结算/buttonbigsecondary_u14_mouseDown.png"}},
{
          "id":"f25dbd4d1b2a4609835cf8cdefc20cde",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'LucidaSans', 'Lucida Sans'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":112,
              "y":494},
            "size":{
              "width":86,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"436a4550bb7049b9a7dcef13cc8a83fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'LucidaSans', 'Lucida Sans'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":112,
                  "y":494},
                "size":{
                  "width":86,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc83b1236721488091a6c80844ac3e5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":107,
              "y":525},
            "size":{
              "width":97,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6421aa036994a918822d9f104b4cf40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":107,
                  "y":525},
                "size":{
                  "width":97,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02478bd63f5d4914880050aaf786e986",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":5,
              "y":43},
            "size":{
              "width":310,
              "height":117}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95d54c572c7e40d890782e622feca707",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":5,
                  "y":43},
                "size":{
                  "width":310,
                  "height":117}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/结算/u22.png"}},
{
          "id":"506884c6ab4849a0a1fdabde2dde4fc7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":60},
            "size":{
              "width":86,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"912d523f3a64438ab2e03337b1cff158",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":60},
                "size":{
                  "width":86,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/结算/u24.png"}},
{
          "id":"dcea320968e043ae9d6c9faaffb9efc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":111,
              "y":68},
            "size":{
              "width":185,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30fd05a56dbd495081f39b182ddc302f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":111,
                  "y":68},
                "size":{
                  "width":185,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"351bcf537e544316b8d643a47538eaa8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":167,
              "y":126},
            "size":{
              "width":38,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"617edb8d9ade46dca6f7405f2a25a0ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":167,
                  "y":126},
                "size":{
                  "width":38,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be4ad9d2b13841bfbdd3b1b8f0e34554",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":204,
              "y":129},
            "size":{
              "width":81,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2db02557693f40a190c7424b372ffd1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":204,
                  "y":129},
                "size":{
                  "width":81,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81e5ebdd34884dd6a0b4feb9f30552ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":107,
              "y":130},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4b6c25d8c3b4e7c94f324c6d6307fd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":107,
                  "y":130},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7aa9a000e33e4679b6bd05cb93379ebe",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":218,
              "y":93},
            "size":{
              "width":76,
              "height":22}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "fd3e78ffd9ea418592c5002e0d8f7bd4":{
      "scriptId":"u0"},
    "0ef3a042aef549d9899552d6fbc24c0c":{
      "scriptId":"u1"},
    "1686b5a58bdc4beab0cd36f51dc17606":{
      "scriptId":"u2"},
    "5e1d4d395770453ba5a0e13b63f519b8":{
      "scriptId":"u3"},
    "c789bc7caf9e4a11ac558cb1265eea00":{
      "scriptId":"u4"},
    "cbf234ebe3a042499a76469ef40ab627":{
      "scriptId":"u5"},
    "ef19eaca1f014c7796f91c8e2d9a5462":{
      "scriptId":"u6"},
    "f7da4226250c4a678b8ed2df46606acf":{
      "scriptId":"u7"},
    "b8781bcccf4d4f34b08414611b7dd6fb":{
      "scriptId":"u8"},
    "b227654ca9024c4a9af37d73ca01affa":{
      "scriptId":"u9"},
    "d5b55ab1b54b407085c76bf8f6c64f36":{
      "scriptId":"u10"},
    "fcb0f033a3bd46afabc694c16ddd1ec6":{
      "scriptId":"u11"},
    "dda341141a75436da8d395b0fbcf48e6":{
      "scriptId":"u12"},
    "33992f34062e48e9ae5a83207d3e5330":{
      "scriptId":"u13"},
    "40824ffd911b4ffa8e13f4cf5c5e2cb9":{
      "scriptId":"u14"},
    "ff22300590314a38aa6e08de7e912e5a":{
      "scriptId":"u15"},
    "61f26f6c556a445a9b8df416ae193e4c":{
      "scriptId":"u16"},
    "5bea06d0273245eeae935fd706ffe5ef":{
      "scriptId":"u17"},
    "f25dbd4d1b2a4609835cf8cdefc20cde":{
      "scriptId":"u18"},
    "436a4550bb7049b9a7dcef13cc8a83fd":{
      "scriptId":"u19"},
    "cc83b1236721488091a6c80844ac3e5b":{
      "scriptId":"u20"},
    "b6421aa036994a918822d9f104b4cf40":{
      "scriptId":"u21"},
    "02478bd63f5d4914880050aaf786e986":{
      "scriptId":"u22"},
    "95d54c572c7e40d890782e622feca707":{
      "scriptId":"u23"},
    "506884c6ab4849a0a1fdabde2dde4fc7":{
      "scriptId":"u24"},
    "912d523f3a64438ab2e03337b1cff158":{
      "scriptId":"u25"},
    "dcea320968e043ae9d6c9faaffb9efc5":{
      "scriptId":"u26"},
    "30fd05a56dbd495081f39b182ddc302f":{
      "scriptId":"u27"},
    "351bcf537e544316b8d643a47538eaa8":{
      "scriptId":"u28"},
    "617edb8d9ade46dca6f7405f2a25a0ec":{
      "scriptId":"u29"},
    "be4ad9d2b13841bfbdd3b1b8f0e34554":{
      "scriptId":"u30"},
    "2db02557693f40a190c7424b372ffd1f":{
      "scriptId":"u31"},
    "81e5ebdd34884dd6a0b4feb9f30552ed":{
      "scriptId":"u32"},
    "f4b6c25d8c3b4e7c94f324c6d6307fd4":{
      "scriptId":"u33"},
    "7aa9a000e33e4679b6bd05cb93379ebe":{
      "scriptId":"u34"}}});